_colors = {
    75: {'LegoColors': ['COP. DIF.'], 'BrickLinkColors': [116]},
    132: {'LegoColors': ['Black Glitter', 'CO.SILVER DIF'], 'BrickLinkColors': [111]},
    1000: {'LegoColors': ['WHITE GLOW'], 'BrickLinkColors': [159]},
    383: {'LegoColors': ['Metalized Silver'], 'BrickLinkColors': [22]},
    15: {'LegoColors': ['White'], 'BrickLinkColors': [1]},
    79: {'LegoColors': ['Nature'], 'BrickLinkColors': [60]},
    335: {'LegoColors': ['Sand red'], 'BrickLinkColors': [58]},
    216: {'LegoColors': ['Rust'], 'BrickLinkColors': [27]},
    4: {'LegoColors': ['Bright red', 'Metallic Bright Red', 'BR.RED', 'MET. BR. RED'], 'BrickLinkColors': [5]},
    12: {'LegoColors': ['Brick Red'], 'BrickLinkColors': [25]},
    86: {'LegoColors': ['BROWN'], 'BrickLinkColors': [91]},
    70: {'LegoColors': ['Reddish Brown', 'RED. BROWN'], 'BrickLinkColors': [88]},
    6: {'LegoColors': ['Earth Orange', 'Sand Yellow Metallic', 'EARTH-ORA', 'MET. EAR.ORA'], 'BrickLinkColors': [8]},
    134: {'LegoColors': ['Copper', 'COPPER INK', 'RED. GOLD', 'COPPER', ' DR.LA.'], 'BrickLinkColors': [84]},
    92: {'LegoColors': ['Nougat'], 'BrickLinkColors': [28]},
    450: {'LegoColors': ['Light Orange Brown'], 'BrickLinkColors': [106]},
    84: {'LegoColors': ['Medium Nougat', 'M. NOUGAT'], 'BrickLinkColors': [150]},
    178: {'LegoColors': ['Gold Metallic', 'MET.SAND.YEL'], 'BrickLinkColors': [81]},
    25: {'LegoColors': ['Bright orange', 'BR.ORANGE'], 'BrickLinkColors': [4]},
    151: {'LegoColors': ['Light stone grey', 'LGH. ST. GREY'], 'BrickLinkColors': [99]},
    484: {'LegoColors': ['Dark Orange', 'DK.ORA'], 'BrickLinkColors': [68]},
    78: {'LegoColors': ['Light Nougat', 'L.NOUGAT'], 'BrickLinkColors': [90]},
    366: {'LegoColors': ['Dark Nougat', 'L.ORABROWN', 'DARK NOUGAT'], 'BrickLinkColors': [29]},
    68: {'LegoColors': ['Light Yellowish Orange'], 'BrickLinkColors': [96]},
    308: {'LegoColors': ['Dark Brown', 'DK. BROWN'], 'BrickLinkColors': [120]},
    462: {'LegoColors': ['Br. yellowish orange', 'BR.YELORA'], 'BrickLinkColors': [31]},
    142: {'LegoColors': ['Gold'], 'BrickLinkColors': [61]},
    297: {'LegoColors': ['Warm Gold', 'W.GOLD'], 'BrickLinkColors': [115]},
    19: {'LegoColors': ['Brick yellow', 'BRICK-YEL'], 'BrickLinkColors': [2]},
    191: {'LegoColors': ['Flame yellowish orange', 'FL. YELL-ORA'], 'BrickLinkColors': [110]},
    28: {'LegoColors': ['Sand yellow'], 'BrickLinkColors': [69]},
    82: {'LegoColors': ['W.GOLD', ' DR.LA.', 'GOLD INK'], 'BrickLinkColors': [65]},
    503: {'LegoColors': ['Light grey'], 'BrickLinkColors': [49]},
    18: {'LegoColors': ['Light yellow'], 'BrickLinkColors': [33]},
    14: {'LegoColors': ['Bright yellow', 'BR.YEL'], 'BrickLinkColors': [3]},
    334: {'LegoColors': ['Metalized Gold'], 'BrickLinkColors': [21]},
    226: {'LegoColors': ['Cool Yellow', 'COOL YEL.'], 'BrickLinkColors': [103]},
    326: {'LegoColors': ['Olive Green', 'OLIVE GREEN'], 'BrickLinkColors': [155]},
    8: {'LegoColors': ['Dark grey', 'DK.GREY'], 'BrickLinkColors': [10]},
    115: {'LegoColors': ['Med. yellowish green'], 'BrickLinkColors': [76]},
    21: {'LegoColors': ['Phosp. White', 'PHOS.WHITE'], 'BrickLinkColors': [46]},
    120: {'LegoColors': ['Lig. yellowish green', 'L.YEL-GREEN'], 'BrickLinkColors': [35]},
    158: {'LegoColors': ['Spring Yellow Green', 'SPR. YELL. GREE'], 'BrickLinkColors': [158]},
    27: {'LegoColors': ['Br. yellowish green', 'BR.YEL-GREEN'], 'BrickLinkColors': [34]},
    81: {'LegoColors': ['Lemon Metallic'], 'BrickLinkColors': [70]},
    72: {'LegoColors': ['Dark stone grey', 'DK. ST. GREY'], 'BrickLinkColors': [85]},
    17: {'LegoColors': ['Light green', 'L.GREEN'], 'BrickLinkColors': [38]},
    10: {'LegoColors': ['Bright Green', 'BR.GREEN'], 'BrickLinkColors': [36]},
    148: {'LegoColors': ['Titanium Metallic', 'Mettalic Dark Grey', 'TITAN. METAL.', 'MET.DK.GREY'], 'BrickLinkColors': [77]},
    183: {'LegoColors': ['Metallic White', 'MET. WHITE'], 'BrickLinkColors': [83]},
    7: {'LegoColors': ['Grey'], 'BrickLinkColors': [9]},
    2: {'LegoColors': ['Dark green', 'Metallic Dark Green', 'DK.GREEN', 'MET. DK. GREEN'], 'BrickLinkColors': [6]},
    378: {'LegoColors': ['Sand green'], 'BrickLinkColors': [48]},
    74: {'LegoColors': ['Medium green', 'MD.GREEN'], 'BrickLinkColors': [37]},
    288: {'LegoColors': ['Earth Green', 'EARTH GREEN'], 'BrickLinkColors': [80]},
    118: {'LegoColors': ['Light bluish green', 'L.BLUE-GREEN'], 'BrickLinkColors': [41]},
    323: {'LegoColors': ['Aqua'], 'BrickLinkColors': [152]},
    3: {'LegoColors': ['Bright bluish green', 'BR.BLUEGREEN'], 'BrickLinkColors': [39]},
    11: {'LegoColors': ['Med. bluish green', 'MD.BL-GREEN'], 'BrickLinkColors': [40]},
    322: {'LegoColors': ['Medium Azure', 'MEDIUM AZUR'], 'BrickLinkColors': [156]},
    232: {'LegoColors': ['Dove blue', 'DO. BLUE'], 'BrickLinkColors': [87]},
    321: {'LegoColors': ['Dark Azur'], 'BrickLinkColors': [153]},
    313: {'LegoColors': ['Pastel Blue', 'PASTBLU'], 'BrickLinkColors': [72]},
    9: {'LegoColors': ['Light blue'], 'BrickLinkColors': [62]},
    135: {'LegoColors': ['Silver flip/flop', 'SILVER'], 'BrickLinkColors': [66]},
    0: {'LegoColors': ['Black', 'Metallic Black', 'BLACK', 'MET.BLACK', 'CONDUCT. BLACK'], 'BrickLinkColors': [11, 94, 151]},
    71: {'LegoColors': ['Medium stone grey', 'MED. ST-GREY'], 'BrickLinkColors': [86]},
    212: {'LegoColors': ['Light Royal blue', 'LGH. ROY. BLUE'], 'BrickLinkColors': [105]},
    272: {'LegoColors': ['Earth blue'], 'BrickLinkColors': [63]},
    1: {'LegoColors': ['Bright Blue', 'Metallic Bright Blue', 'BR.BLUE', 'MET. BR. BLUE'], 'BrickLinkColors': [7]},
    73: {'LegoColors': ['Medium blue', 'MD.BLUE'], 'BrickLinkColors': [42]},
    137: {'LegoColors': ['Sand blue metallic', 'Metal Blue', 'MET.SAND.BLU'], 'BrickLinkColors': [78]},
    379: {'LegoColors': ['Sand blue'], 'BrickLinkColors': [55]},
    80: {'LegoColors': ['C.SILVER', ' DR. L', 'SILVER INK', 'C.SILVER'], 'BrickLinkColors': [67]},
    110: {'LegoColors': ['Bright Bluish Violet', 'BR.BLUEVIOL', 'LILAC'], 'BrickLinkColors': [43]},
    23: {'LegoColors': ['Dark Royal blue', 'DK. R.BLUE'], 'BrickLinkColors': [109]},
    112: {'LegoColors': ['Medium Bluish Violet', 'R.BLUE'], 'BrickLinkColors': [97]},
    20: {'LegoColors': ['Light bluish violet', 'L.BLUEVIOL'], 'BrickLinkColors': [44]},
    1001: {'LegoColors': ['RED. LILAC', 'ML.BLUEVIOL'], 'BrickLinkColors': [73]},
    85: {'LegoColors': ['Medium Lilac', 'M. LILAC'], 'BrickLinkColors': [89]},
    31: {'LegoColors': ['Lavender'], 'BrickLinkColors': [154]},
    30: {'LegoColors': ['Medium Lavender', 'MEDIUM LAVENDEL'], 'BrickLinkColors': [157]},
    373: {'LegoColors': ['Sand violet'], 'BrickLinkColors': [54]},
    22: {'LegoColors': ['Bright violet', 'BR. VIOLET'], 'BrickLinkColors': [24]},
    26: {'LegoColors': ['Bright reddish violet', 'BR.RED-VIOL.'], 'BrickLinkColors': [71]},
    5: {'LegoColors': ['Bright Purple', 'BR. PURPLE'], 'BrickLinkColors': [47]},
    69: {'LegoColors': ['Bright Reddish Lilac', 'BR. RED. LILAC'], 'BrickLinkColors': [93]},
    179: {'LegoColors': ['Silver Metallic', 'SILVER MET.'], 'BrickLinkColors': [95]},
    29: {'LegoColors': ['Light Purple', 'LGH. PURPLE'], 'BrickLinkColors': [104]},
    13: {'LegoColors': ['L.REDVIOL'], 'BrickLinkColors': [23]},
    77: {'LegoColors': ['Light Pink'], 'BrickLinkColors': [56]},
    100: {'LegoColors': ['Light red'], 'BrickLinkColors': [26]},
    320: {'LegoColors': ['Dark red', 'NEW DARK RED'], 'BrickLinkColors': [59]},
    47: {'LegoColors': ['Transparent', 'TR.'], 'BrickLinkColors': [12]},
    117: {'LegoColors': ['Transparent Glitter', 'TR.W.GLITTER'], 'BrickLinkColors': [101]},
    36: {'LegoColors': ['Tr. Red', 'TR.RED'], 'BrickLinkColors': [17]},
    57: {'LegoColors': ['Tr. Flu. Reddish orange', 'TR.FL.REDORA'], 'BrickLinkColors': [18]},
    182: {'LegoColors': ['Tr. Bright Orange', 'TR. BR. ORANGE'], 'BrickLinkColors': [98]},
    40: {'LegoColors': ['Tr. Brown', 'TR.BROWN'], 'BrickLinkColors': [13]},
    46: {'LegoColors': ['Tr. Yellow', 'TR.YEL'], 'BrickLinkColors': [19]},
    54: {'LegoColors': ['Transparent Fluorescent Yellow'], 'BrickLinkColors': [121]},
    42: {'LegoColors': ['Tr. Flu. Green', 'TR.FL.GREEN'], 'BrickLinkColors': [16]},
    35: {'LegoColors': ['Transparent Bright Yellowish Green', 'Transparent Bright Green', 'TR. BR. YEL GR', 'TR. BR. GREEN'], 'BrickLinkColors': [108]},
    1002: {'LegoColors': ['TR.FL.GRE W/GLI'], 'BrickLinkColors': [163]},
    294: {'LegoColors': ['Phosphorescent Green', 'PH.GREEN'], 'BrickLinkColors': [118]},
    34: {'LegoColors': ['Tr. Green', 'TR.GREEN'], 'BrickLinkColors': [20]},
    41: {'LegoColors': ['Tr. Lg blue', 'TR.L.BLUE'], 'BrickLinkColors': [15]},
    1003: {'LegoColors': ['PCTR LI.BLUE W/'], 'BrickLinkColors': [162]},
    43: {'LegoColors': ['Transparent Light Bluish Green', 'TR. LGH. BL. GR'], 'BrickLinkColors': [113]},
    143: {'LegoColors': ['Tr. Flu. Blue', 'TR.FL. BLUE'], 'BrickLinkColors': [74]},
    33: {'LegoColors': ['Tr. Blue', 'TR.BLUE'], 'BrickLinkColors': [14]},
    52: {'LegoColors': ['Tr. Bright bluish violet', 'TR.KL.BL.VIO'], 'BrickLinkColors': [51]},
    129: {'LegoColors': ['Tr. Bright Bluish Violet w. Glitter 2%', 'TR.BR.BL.V.G'], 'BrickLinkColors': [102]},
    45: {'LegoColors': ['Tr. Medi. reddish violet', 'TR.ML.R.VIOL'], 'BrickLinkColors': [50]},
    114: {'LegoColors': ['Tr. Medium Reddish-Violet w. Glitter 2%', 'TR.M.R.V.GLI'], 'BrickLinkColors': [100]},
}


def rebrickable_color_id_from_bricklink_color_id(bl_color_id: int) -> int:
    for re_id, props in _colors.items():
        for bl_id in props['BrickLinkColors']:
            if bl_id == bl_color_id:
                return re_id
    raise KeyError(bl_color_id)


def color_name_from_rebrickable_color_id(re_color_id: int) -> str:
    assert re_color_id in _colors
    return _colors[re_color_id]['LegoColors'][0]
